
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MirrorRepository.Data.SnowDbSyncMgnt
{
    using Helpers;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DatabaseSettings")]
    public partial class DatabaseSettings : ICloneable, ICopyable<DatabaseSettings>
    {

        [Key]
        public System.Guid Id { get; set; }

        public string Servername { get; set; }

        public int Port { get; set; }

        public string Instancename { get; set; }

        public string Databasename { get; set; }

        public string Schemaname { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public System.DateTime Created { get; set; }

        public System.DateTime LastChanged { get; set; }

        public DatabaseSettings Copy()
        {
            return (DatabaseSettings)Clone();
        }
        public override string ToString()
        {
            return GetType().Name + "[" + Id + "]: name=" + Instancename + ", user=" + Username + ", cnx=" + Databasename + "/" + Servername + ":" + Port;
        }
        public object Clone()
        {
            var clone = ReflectionHelper.CopyProps(this);
            return clone;
        }
    }

}
