
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MirrorRepository.Data.SnowDbSyncMgnt
{
    using MirrorRepository.Helpers;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("InstanzSettings")]
    public partial class InstanzSettings : ICloneable, ICopyable<InstanzSettings>
    {

        [Key]
        public System.Guid Id { get; set; }

        public string InstanzName { get; set; }

        public string Servername { get; set; }
        
        public int Port { get; set; }

        public string UserName { get; set; }

        public string Password { get; set; }

        public string ProxyServer { get; set; }

        public string ProxyUserName { get; set; }

        public string ProxyUserPassword { get; set; }

        public Nullable<int> ProxyPort { get; set; }

        public Nullable<System.DateTime> LastChanged { get; set; }

        public Nullable<System.DateTime> Created { get; set; }
        
        public InstanzSettings Copy()
        {
            return (InstanzSettings)Clone();
        }
        public override string ToString()
        {
            return GetType().Name + "[" + Id + "]: name=" + InstanzName;
        }
        public object Clone()
        {
            var clone = ReflectionHelper.CopyProps(this);
            return clone;
        }
    }

}
