//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirrorRepository.Data.SnowDbSyncMgnt
{
    using MirrorRepository.Model;
    //using System.Data.Entity;
    using Microsoft.EntityFrameworkCore;


    public partial class ServiceNowDbSyncMgntEntitiesGenerated : DbContext
    {
        public ServiceNowDbSyncMgntEntitiesGenerated()
//            : base("name=ServiceNowDbSyncMgntEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    //throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<DatabaseSettings> DatabaseSettings { get; set; }

        public virtual DbSet<InstanzSettings> InstanzSettings { get; set; }

        public virtual DbSet<AppSettings> AppSettings { get; set; }

        public virtual DbSet<ServiceSettings> ServiceSettings { get; set; }

        public virtual DbSet<SyncProcess> SyncProcess { get; set; }
        
        public virtual DbSet<SyncType> SyncType { get; set; }

        public virtual DbSet<SyncTarget> SyncTarget { get; set; }

        public virtual DbSet<Synchronization> Synchronization { get; set; }
        
        public virtual DbSet<ManagementRole> ManagementRole { get; set; }
        
        public virtual DbSet<Principals> Principals { get; set; }

        public virtual DbSet<NotificationHistory> NotificationHistory { get; set; }

        public virtual DbSet<SnowTableDefinition> SnowTableDefinition { get; set; }

        public virtual DbSet<TableMonitoring> TableMonitoring { get; set; }

    }
}
