
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MirrorRepository.Data.SnowDbSyncMgnt
{
    using MirrorRepository.Base;
    using MirrorRepository.Helpers;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SyncProcess")]
    public partial class SyncProcess : ICloneable, ICopyable<SyncProcess>
    {
        [Key]
        public string Key { get; set; }

        public System.Guid SynchronizationId { get; set; }

        public string TableName { get; set; }

        public Guid? SysId { get; set; }

        public System.DateTime? ServiceStartTime { get; set; }

        public System.DateTime? StartTime { get; set; }

        public System.DateTime? SyncTime { get; set; }

        public System.DateTime? EndTime { get; set; }

        public System.DateTime? PreviousEndTime { get; set; }
        
        public System.DateTime? PreviousStartTime { get; set; }

        public DateTime? GetDeltaRecordsFrom { get; set; }
        
        public int RecordsSynchronized { get; set; }

        public int RecordsInserted { get; set; }

        public int RecordsUpdated { get; set; }
        public int RecordsDeleted { get; set; }

        public int RecordsFound { get; set; }

        public int Pages { get; set; }

        public int Page { get; set; }
        
        public int Failures { get; set; }
        
        public int MaxFailures { get; set; }
        
        public int MaxFailuresPage { get; set; }
        
        public System.DateTime Created { get; set; } = DateTime.Now;

        public string FinalMessage { get; set; }

        public string FinalErrorMessage { get; set; }

        public string Messages { get; set; }

        public int? ThreadsPerTable { get; set; }

        public int? ThreadSleepTime { get; set; }

        public int? PageSize { get; set; }

        public int? RequestTimeout { get; set; }

        public bool StopProcess { get; set; }

        public bool SuspendProcess { get; set; }

        [NotMapped]
        public List<LogMessage> LogMessages
        {
            get { return LogMessage.Deserialize(Messages); }
            set { Messages = LogMessage.Serialize(value); }
        }

        [ForeignKey("SynchronizationId")]
        public virtual Synchronization Synchronization { get; set; }

        public override string ToString()
        {
            return GetType().Name + "[" + Key + "]: sync=" + SynchronizationId + ", table=" + TableName + ", start=" + StartTime + "/" + SyncTime + "/" + EndTime + ", page=" + Page + "/" + Pages ;
        }


        public SyncProcess Copy()
        {
            return (SyncProcess)Clone();
        }

        public object Clone()
        {
            return ReflectionHelper.CopyProps(this);
        }
    }

}
