//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirrorMonitoring.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MonitorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonitorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MirrorMonitoring.Resource.MonitorResource", typeof(MonitorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos;&gt;
        ///&lt;div id=&quot;header-img&quot;&gt;
        ///	&lt;img width=&quot;595&quot; height=&quot;66&quot; id=&quot;_x0000_i1025&quot; alt=&quot;alertheader&quot; src=&apos;https://vmsnwwp110.isp.local/MirrorWeb/content/images/SnowDbSyncAlert.jpg&apos; border=&quot;0&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;div id=&quot;intro&quot; style=&quot;color: black; font-family: Verdana, sans-serif; font-size: 9pt;&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;Hello SnowDbSync Admin/Support!&lt;/span&gt; 
        ///	&lt;br /&gt;
        ///	&lt;br /&gt;
        ///	&lt;span&gt;This is an automatic alert warning from ServiceNOW da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeltaAlert {
            get {
                return ResourceManager.GetString("DeltaAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos;&gt;
        ///&lt;div id=&quot;header-img&quot;&gt;
        ///	&lt;img width=&quot;595&quot; height=&quot;66&quot; id=&quot;_x0000_i1025&quot; alt=&quot;alertheader&quot; src=&apos;https://vmsnwwp110.isp.local/MirrorWeb/content/images/SnowDbSyncAlert.jpg&apos; border=&quot;0&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;div id=&quot;intro&quot; style=&quot;color: black; font-family: Verdana, sans-serif; font-size: 9pt;&quot;&gt;
        ///    &lt;span style=&quot;font-weight: bold&quot;&gt;Hello SnowDbSync Admin/Support!&lt;/span&gt; 
        ///	&lt;br /&gt;
        ///	&lt;br /&gt;
        ///	&lt;span&gt;This is an automatic alert warning from ServiceNOW da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FailedTableAlert {
            get {
                return ResourceManager.GetString("FailedTableAlert", resourceCulture);
            }
        }
    }
}
